In [14]:
import numpy as np

In [27]:
#the matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

In [16]:
# the inverse (transpose) of the matrix
inverse_matrix = np.linalg.inv(matrix)

In [17]:
print("Matrix:")
print(matrix)

Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [18]:
print("\nInverse (Transpose) Matrix:")
print(inverse_matrix)


Inverse (Transpose) Matrix:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [19]:
#the deteminant of the matrix

In [20]:
import numpy as np

In [28]:
#the matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

In [22]:
#the determinant of the matrix
determinant = np.linalg.det(matrix)

In [23]:
print("Determinant of the Matrix:", determinant)

Determinant of the Matrix: 0.2299999999999999


In [24]:
#decompose the matrix

In [25]:
import numpy as np

In [29]:
#the matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

In [30]:
#decompose the matrix
decompose = np.linalg.cholesky(matrix)

In [31]:
cholesky_matrix = np.linalg.cholesky(matrix)

In [32]:
print("Cholesky Decomposition:")

Cholesky Decomposition:


In [33]:
print(cholesky_matrix)

[[1.         0.         0.        ]
 [0.2        0.9797959  0.        ]
 [0.5        0.71443451 0.48947251]]
